### ISSUE TITLE
[1.12.2] ID warnings...

### ISSUE THREAD

**Issue by PhoenixRiver** [GirafiStudios/Waddles#10]
Version: Waddles-1.12.2-0.5.6
Forge: forge1.12.2-14.23.1.2555

These warnings appeared when I ran minecraft - I can provide a modlist if that is of any help though it looks like Waddles doesn't do dynamic IDs? For reference I'm not running any sound mods (in case that is part of the issue).

```
[17:50:43] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: waddles:adelie.ambient Expected: 603 Got: 622
[17:50:43] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: waddles:adelie.death Expected: 605 Got: 623
[17:50:43] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: waddles:adelie.baby.ambient Expected: 604 Got: 624
[17:50:43] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: waddles:adelie.hurt Expected: 606 Got: 625
[17:50:43] [Server thread/WARN] [FML]: Registry EntityEntry: Object did not get ID it asked for. Name: waddles:adelie_penguin Expected: 131 Got: 140
```

Hope this helps.

**Comment by GirafiStudios** [comment]
Did you update your world from an older MC version, or the first 1.12 version of Waddles?

**Comment by PhoenixRiver** [comment]
I have updated from an earlier version of Waddles... should I be
removing the old config file then?

This is what it looks like:
```
# Configuration file

general {
    B:"Enable that penguins drop fish (0 - 2 Raw fish)"=false
    B:"Penguins should drop experience?"=true
}


##########################################################################################################
# spawn chances
#--------------------------------------------------------------------------------------------------------#
# Configure penguins spawn weight & min/max group size. Set weight to
0 to disable.
##########################################################################################################

"spawn chances" {

    adelie_penguin {
        I:Max=4
        I:Min=1
        I:Weight=2
    }

}
```

**Comment by GirafiStudios** [comment]
Doubt that will help, but you could try.
Does this happen every time you load op a world? And does it happen if you load up a new world?

**Comment by PhoenixRiver** [comment]
I've checked for it the two times since that I've loaded Minecraft and
it didn't come up, I presume it is something to do with load order and
that that time another mod loaded before rather than after yours...
though given that it starts with a "w" I'd guess after is more likely
than before assuming it is sorting IDs at the same stage - it might
also be that I was exploring and now I'm not so no loaded chunks have
penguins? (I'll check if I get it again at what point in the load
order it comes but I though it was before map load so... *shrug*)

Thank you for taking a look at it and hopefully it's nothing serious
and not a very random intermittent (those bugs are always the worst :(

**Comment by GirafiStudios** [comment]
You are welcome, and thanks for reporting :)
It should not be anything serious. Worst case scenario the penguins that was loaded in to your world previously might disappear.
