### ISSUE TITLE
No loot table

### ISSUE THREAD

**Issue by darkhax** [GirafiStudios/Waddles#11]
The penguin doesn't have a loot table. Shouldn't it be empty rather than null?

**Comment by GirafiStudios** [comment]
Well maybe. Is it causing some sort of issue because it is null?

**Comment by darkhax** [comment]
It means that penguins can not have their drops modified by mods that edit the loot table. I am also working on a mod that uses the loot table data so this would cause incompatibilities there.

**Comment by GirafiStudios** [comment]
I guess yea. Only really thought of a way of modpack makers  to modify the penguin drops (Can just enable the fish dropping, and then alter that loot table).
Will just add a empty loot table by default I guess :)
