### ISSUE TITLE
[1.14.3] Spawning issue - under the ice.

### ISSUE THREAD

**Issue by ProsperCraft** [GirafiStudios/Waddles#18]
![2019-07-16_19 38 04](https://user-images.githubusercontent.com/4427684/61340862-67b72400-a801-11e9-8a36-eb93347f268c.png)

**Comment by GirafiStudios** [comment]
This is was actually caused by Forge.
Unfortunately it's not actually possible to make the Adélie Penguins spawn on the ice, since the ice only allows for Polar Bears to spawn on them.
