### ISSUE TITLE
Waddles needs a mob spawn limit

### ISSUE THREAD

**Issue by Sunconure11** [GirafiStudios/Waddles#2]
While trying to diagnose lag and deadlocking in a pack I'm building, I've noticed this:

![screenshot 2017-06-22 23 10 08](https://user-images.githubusercontent.com/5614902/27465236-2df8b3ea-57a0-11e7-83ec-e00e690600ef.png)
107 Penguins.

**Comment by GirafiStudios** [comment]
Please specify version and biome it occurred in.

**Comment by Sunconure11** [comment]
Fuck, I actually forgot the biome, since I deleted the world, but it was on Forge 1.11.2, using build 2315 of Forge, and 0.5.2 for 1.11.2. It was one of BoP's cold biomes IIRC, though.

**Comment by GirafiStudios** [comment]
Thanks for the report!
That is is a cold BoP biome is all I needed to know really. Because it could actually be caused by them.
But I'm currently on holiday until the middle of next week, so I most likely won't be able to take a look at this, until then.

**Comment by GirafiStudios** [comment]
I have fixed this locally. A new version will be out for all versions later, when the new Forge recommended build hits for 1.12 (Should be sometime in the evening PDT)
