### ISSUE TITLE
[1.14.4] CME on loading causing a crash on startup.

### ISSUE THREAD

**Issue by ProsperCraft** [GirafiStudios/Waddles#20]
Stacktrace from console-
https://gist.github.com/ProsperCraft/feae7192bae0cd4bf57813bfdfe2e9e2
and
https://gist.github.com/ProsperCraft/3506440691287d2f8899d88c6baf36cf

Waddles-1.14.4-0.8.2
forge-1.14.4-28.0.49

Restarted another time and it loaded without a crash.

Restarted another time and it crashed with -

https://gist.github.com/ProsperCraft/ca0c4e5b2766310c41a9205dcfbc17bb

**Comment by Shadows-of-Fire** [comment]
You need to wrap your call to addSpawn() in a DeferredWorkQueue.runLater call due to threaded loading

**Comment by GirafiStudios** [comment]
Thanks for the report!
Also thanks for the solution, I'm unfortunately not currently home - I'll take a look at it Sunday most likely.

**Comment by GirafiStudios** [comment]
@ProsperCraft I was not able to reproduce the crash after around 10 launches. I did the suggested fix by Shadows-of-Fire though. Could you check if it works for you?
You can grab the build here: https://jenkins.girafi.dk/job/Waddles/job/Waddles%201.14/6/
Please respond if it works for you or not :)

**Comment by ProsperCraft** [comment]
We test on a live server with players pulling updates from curse, please push to curse and will test.

**Comment by ProsperCraft** [comment]
Did you use my pack for the launches? because you won't have a concurrent modification obviously without other things trying to modify :) Just a passing thought :)

https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by GirafiStudios** [comment]
I would love to take a look myself using that modpack, but unfortunately the Twitch Launcher does not like Forge for 1.13+. I thought that was an issue everybody had?

**Comment by ProsperCraft** [comment]
I have worked through some of the issues with the Twitch devs and got them fixed.

There are remedies for the current known issues in my modpack description.

**Comment by GirafiStudios** [comment]
I got it working by manually installing Forge.
It says it can't find Forge when I'm trying to add a new instance on the launcher (Unless I've installed Forge manually first). Already reported this issue to the launcher devs like a month or two ago.

**Comment by GirafiStudios** [comment]
Launched the server around 10 times now, the issue does not occur for me.
Maybe it's Linux Server/Windows Server issue only - whichever you guy are using.

**Comment by Shadows-of-Fire** [comment]
Well its a thread issue, so it's very much hardware dependent.

**Comment by GirafiStudios** [comment]
You're correct, yea. I did manage to reproduce it once.
Uploaded the new build to CurseForge now. Please let me know if it fixes it for you @ProsperCraft, once you have time
