### ISSUE TITLE
0.8.6 incorrectly marked Fabric on curseforge

### ISSUE THREAD

**Issue by Linguardium** [GirafiStudios/Waddles#22]
![image](https://user-images.githubusercontent.com/61733861/77862546-130dda80-71d1-11ea-9578-afe84324de1f.png)
https://www.curseforge.com/minecraft/mc-mods/waddles/files/2916036

(though i would love to see Fabric 1.15 release ;) )

**Comment by GirafiStudios** [comment]
Thanks for informing me :)
