### ISSUE TITLE
Penguins not rendering properly

### ISSUE THREAD

**Issue by develgool** [GirafiStudios/Waddles#26]
I noticed a unusual number of pigs in my snowy biome and upon further look they appear to be the penguins this mod gives me. They do not walk like normal pigs nor do they drop pork when killed. I am sad to see this as I was looking forward to having penguins in my server.

**Comment by GirafiStudios** [comment]
Could you provide a screenshot?

**Comment by develgool** [comment]
![image](https://user-images.githubusercontent.com/77503598/104757105-a2698780-572a-11eb-8587-cf0fe54c6bce.png)

I did up the amount of penguins that would spawn in a group because I thought they where rare. This is out in the middle of the snowy biome with a regular biome not for hundreds of blocks.

**Comment by develgool** [comment]
I have killed another pig and it dropped a fish. These are definitely supposed to be my penguins.

**Comment by GirafiStudios** [comment]
What version of Waddles are you using?

**Comment by develgool** [comment]
The most recent one. 1.16.4-0.8.11

**Comment by GirafiStudios** [comment]
That's your problem right there, using Aternos. It doesn't work with a lot of things.
