### ISSUE TITLE
cant danload penguin mod on macOS

### ISSUE THREAD

**Issue by penguiniscute** [GirafiStudios/Waddles#27]
I tried to download it on my mac but it could not open I am a big fan of penguins. I think it didn't open because mac use javascript, I searched it up on the curse forge app and i couldn't find it. pls recode it for macOS and pls put it on the app.

**Comment by GirafiStudios** [comment]
It's fully compatible with MacOS and it is on the CurseForge launcher.
Sounds like you're having trouble using the CurseForge launcher.

**Comment by penguiniscute** [comment]
Uploading Screen Recording 2021-03-29 at 8.49.20 pm.mov…

**Comment by penguiniscute** [comment]
https://user-images.githubusercontent.com/81516942/112891769-6e1e2a00-90d0-11eb-80b1-939a1f55085e.mov

**Comment by penguiniscute** [comment]
I tryed a lot of times and it still dosent work all the other mods work

**Comment by GirafiStudios** [comment]
You're searching for modpacks..
You need to select "Create Custom Profile" (Your own modpack) in the top right corner.
Select "1.16.5" and Forge 36.1.0
Then "Add More Content" and search for Waddles.

**Comment by penguiniscute** [comment]
thanks it worked :)
