### ISSUE TITLE
Penguins not spawning?

### ISSUE THREAD

**Issue by MJRLegends** [GirafiStudios/Waddles#3]
Hello, i just tried out your mod in my pack and they dont seem to spawn

Example Frozen Ocean:
![2017-07-07_22 29 37](https://user-images.githubusercontent.com/8526321/27977727-f35ad9d2-6363-11e7-9c21-226b83123222.png)

i even checked my biomes and it registered with the correct biome dictionary
`minecraft:frozen_ocean,10,FrozenOcean,0.0,0.5,0.1,-1.0,0.1,"COLD, OCEAN, SNOWY",net.minecraft.world.biome.BiomeOcean`

**Comment by MJRLegends** [comment]
Any ideas, im probably doing something wrong haha also here is a mod list of what im using in my pack: https://pastebin.com/8uF9P9jh

**Comment by GirafiStudios** [comment]
No mobs are supposed to spawn in the Frozen Ocean biome, therefore penguins do not spawn there. Works in ice plains etc.

**Comment by MJRLegends** [comment]
Thanks for your reply but they dont even spawn on a Ice Plains for me either :/ 
![2017-07-07_22 48 41](https://user-images.githubusercontent.com/8526321/27978279-719a58b6-6366-11e7-9edd-eff6fa9186ff.png)

Also i got Frozen Ocean from your curse page 
![](https://i.gyazo.com/ea680103ea5fc77e4071b88fd143f5da.png)

**Comment by GirafiStudios** [comment]
Yea that changed recently. Forgot to change the page. They do indeed spawn in ice plains, they are just rare :)

**Comment by MJRLegends** [comment]
@GirafiStudios No problem, any chance of a config option to change the rate of spawning? it would be great if you could :D

**Comment by GirafiStudios** [comment]
I can add a config for the min/max weight for sure. I will see if I can get it done during the next week.

**Comment by MJRLegends** [comment]
Thank you that will be great also i have found one now 
![2017-07-07_22 54 54](https://user-images.githubusercontent.com/8526321/27978436-573376c8-6367-11e7-835c-b44f3de01015.png)
