### ISSUE TITLE
Crash when killing or damaging penguins

### ISSUE THREAD

**Issue by Foozey** [GirafiStudios/Waddles#30]
Same crash as the other person that posted the issue that you closed. Happens every time without fail, not random.

Latest version of Waddles as of this post (1.16.5-0.8.12). Haven't posted the crash log due to it matching the one posted by the other person.

**Comment by GirafiStudios** [comment]
I was closing it, as he did not provide a full crashlog, and pasted it directly into Github. So I still don't have a proper crash report.
