### ISSUE TITLE
Killing Adelie penguin crashes server

### ISSUE THREAD

**Issue by foughtgodandlost** [GirafiStudios/Waddles#31]
Hi! I made a github just to report this bug. 
I have the waddles mod along with valhelsia 3 and a bunch of other random mods. For some reason if the penguin dies, the server crashes. It doesn't matter if it's naturally spawned, summoned, or spawned with an egg.
We've tested this by killing it in the following ways;

- Blew it up with a Blue Pets creeper
- Punched it to death
- made it fall in lava
- killed it with wolves

Just a heads up for people that use the mod. I don't know if it's a preprogrammed thing, or if it's a conflict with one of the many mods we have. 
I recommend labeling it god and not touching it.

**Comment by GirafiStudios** [comment]
What version of Waddles are you using?

**Comment by GirafiStudios** [comment]
Closing because of no response. This should be fixed in Waddles version 0.8.13
