### ISSUE TITLE
NOT AN ISSUE, JUST THANK YOU A LOT!!!

### ISSUE THREAD

**Issue by MadAlchemist** [GirafiStudios/Waddles#37]
Hi! I am author of Zombienation mod, and it is your penguin mod Waddles what helped me to fugure out how to add entities to newer versions of minecraft at all! Clear, simple, comprehensible sources, better than any tutorial - especially now, when most coding tutorials come in video. Thanks you again!

**Comment by GirafiStudios** [comment]
Thank you very much, for the kind words! :)
I´m glad Waddles source have been of help to you! I do indeed try to keep it as simple as possible :)
