### ISSUE TITLE
Breedable penguins and drops!

### ISSUE THREAD

**Issue by ShaunDreclin** [GirafiStudios/Waddles#4]
Are the penguins breedable? If not, they should be! Maybe with raw fish as their item

Also they should drop feathers/eggs like chickens do :D so we can have penguin farms instead of chicken farms

**Comment by MJRLegends** [comment]
Yeah that would be amazing :D

**Comment by GirafiStudios** [comment]
The penguins are already breedable with raw fish or raw salomon.
There is a config option for penguins to drop fish. If you wish them to drop something else you can also turn on that config option and then change with a resourcepack what you want them to drop.
