### ISSUE TITLE
1.20.2 port

### ISSUE THREAD

**Issue by gohkenytp** [GirafiStudios/Waddles#40]
I hate to do this, but is it possible to port this mod to 1.20.2? Thank you!

**Comment by GirafiStudios** [comment]
I didn´t even know 1.20.2 was out honestly!
Is it not working for 1.20.2?

**Comment by gohkenytp** [comment]
Well, I tried to use it on 1.20.2, but no use.

**Comment by GirafiStudios** [comment]
It already works just fine on 1.20.2, it just wasn´t marked as 1.20.2 on CurseForge :)
