### ISSUE TITLE
How to config penguin spawn?

### ISSUE THREAD

**Issue by mrnoonx** [GirafiStudios/Waddles#41]
I'm trying to add the penguins to new biomes that are added because of other mods but in the waddles-common config it only shows the loot table. How would I get to the spawning config?

**Comment by GirafiStudios** [comment]
You would have to use a data/resourcepack, to alter the biome modifier. It's the only way it's possible to add mob spawns nowadays with Forge & it's not possible to have spawn rates in the config anymore unfortunately.

https://github.com/GirafiStudios/Waddles/blob/master/src/main/resources/data/waddles/forge/biome_modifier/add_penguin_spawn.json
