### ISSUE TITLE
Idea: Modrinth release

### ISSUE THREAD

**Issue by vico93** [GirafiStudios/Waddles#42]
Could you guys release Waddles on Modrinth as well?

Every passing day CurseForge became more and more insalubre for the end user to navigate (specially after the UI change), while Modrinth are far more user-friendly, incorporates the collection functionality of other social medias (basically organize favorite mods by categories), and have a nice API that is even used by Mod Menu to warn the user about mod updates.

**Comment by vico93** [comment]
> Probably not atm., seems the approval times is extremely long, which I simply don't want to deal with. Maybe sometime in the future.

Strange... i always heard in Fabric's Discord that it was quite the opposite... Modrinth faster to approve than CF.

**Comment by GirafiStudios** [comment]
Took almost 1 month to get another project approved on Modrinth.

**Comment by vico93** [comment]
Bumping the issue to see if @GirafiStudios changed his mind on the meanwhile. CurseForge is becoming harder and harder to track mod updates (currently i'm using Modrinth's follow feature to do it).
