### ISSUE TITLE
problem with the penguins

### ISSUE THREAD

**Issue by derLasercutter** [GirafiStudios/Waddles#43]
If I try to spawn them with the spawn egg my game will instandly crash. I use the Forge 1.20.1 version.

**Comment by GirafiStudios** [comment]
Could you please provide the crash log?

**Comment by derLasercutter** [comment]
Sorry I don't know how I do that.

**Comment by GirafiStudios** [comment]
Unable to reproduce on Forge 1.20.1
As you´ve provided literally no information, I can´t really do much.

My best suggestion would be to update Forge, you´re probably using an old version.

**Comment by derLasercutter** [comment]
Never Mind. The Mod got a Update direktly after I installed it.😅It works now.
