### ISSUE TITLE
Penguin ID for Manure mod blacklist?

### ISSUE THREAD

**Issue by idk-jer** [GirafiStudios/Waddles#44]
This is an amazing mod, thank you for creating it! I'm not very good with mods, so I was wondering if you could help me with something weird.
Random, but I have the Manure mod on my server with my friends and the penguins won't stop dropping manure lol. There's a blacklist config for the Manure mod, but I can't figure out what I'd need to type in the blacklist.txt for the penguins. Vanilla mobs are blacklisted like this "!minecraft:ocelot" if that helps.

**Comment by GirafiStudios** [comment]
waddles:adelie_penguin is they registry name :)
