### ISSUE TITLE
1.21 port

### ISSUE THREAD

**Issue by jquann1998** [GirafiStudios/Waddles#45]
I hate to do this, but is it possible to port this mod to 1.21? Thank you!

**Comment by GirafiStudios** [comment]
I honestly had no clue 1.21 was out yet. I´ll take a look at it later - hopefully! :)

**Comment by jquann1998** [comment]
Good thinking. Hope it get released soon. 👍

**Comment by GirafiStudios** [comment]
It´s available on Jenkins (No Forge for now, cause of Architechtry Loom not support Forge for 1.21 yet) :)
https://jenkins.girafi.dk/job/Waddles/job/Waddles%201.21/

**Comment by sunbatheproductions** [comment]
Minecraft 1.21.5 just released today and was wondering if you can port your mods to that version

**Comment by GirafiStudios** [comment]
Yes, at some point for sure!
