### ISSUE TITLE
Waddles Stops Statistics Page From Loading

### ISSUE THREAD

**Issue by Darkosto** [GirafiStudios/Waddles#6]
Hey Girafi!

Over the last couple of weeks, when clicking on the statistics page while playing a world, the screen is stuck on "downloading statistics". I spent some time today tracking down which mod is causing this and discovered it's Waddles. It happens when only Waddles is installed, so I don't think it's a mod compat issue. 

MC: 1.12 and 1.12.1
Waddles: 0.5.4

Thank you!
Darkosto

**Comment by GirafiStudios** [comment]
Thanks a lot for the report!
I will look into it as soon as possible. Not quite sure what would be causing it though.
