### ISSUE TITLE
pt_BR Translation

### ISSUE THREAD

**Issue by InterPlay02** [GirafiStudios/Waddles#8]
Hello!

I've made a Brazilian Portuguese Translation:
https://pastebin.com/ECTpggic
I hope you use it in future releases... =)

**Comment by GirafiStudios** [comment]
Thanks for the translation!
Do you know how to make a pull request? If so, please do - if not I will manually add it later :)

**Comment by InterPlay02** [comment]
No, I don't...

**Comment by GirafiStudios** [comment]
Alright, fair enough :)
I will get around to doing it later then!

**Comment by GirafiStudios** [comment]
Added in https://github.com/GirafiStudios/Waddles/commit/ad787e107f48845a9a7ef28c1f46574daa26f143
Will be part of the next Waddles update :)
